version: 0.0
os: linux
files:
  - source: sample-app-1.0.jar
    destination: /var/sample-app/sample-app.jar
permissions:
  - object: /var/sample-app
    owner: sample-app-user
    group: sample-app-user
hooks:
  ApplicationStop:
    - location: scripts/stop-service.sh
      timeout: 60
      runas: root
    - location: scripts/backup-previous-deployments.sh
      timeout: 60
      runas: root
  BeforeInstall:
    - location: scripts/install-dependencies.sh
      timeout: 180
      runas: root
  AfeterInstall:
    -	location: scripts/install-service.sh
      timeout: 60
      runas: root
  ApplicationStart:
    - location: scripts/start-service.sh
      timeout: 180
      runas: root
  ValidateService:
    - location: scripts/validate.sh
      timeout: 180
      runas: root
